// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hint-frames/AmberTargetMarker.tsx": () => import("../components/mockups/hint-frames/AmberTargetMarker.tsx"),
  "./components/mockups/hint-frames/BlueCornerBrackets.tsx": () => import("../components/mockups/hint-frames/BlueCornerBrackets.tsx"),
  "./components/mockups/hint-frames/WhiteDoubleFrame.tsx": () => import("../components/mockups/hint-frames/WhiteDoubleFrame.tsx")
};
